default_stages: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11 # Use the latest version if different
    hooks:
      # the linter
      - id: ruff
        args: [--fix] # auto-apply fix where possible
      # the formatter
      - id: ruff-format
