services:
    db:
        image: tensorchord/vchord-postgres:pg18-v1.1.0
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5435:5432"
        volumes:
            - db_data:/var/lib/postgresql
            - ./initdb:/docker-entrypoint-initdb.d
        restart: always

volumes:
    db_data:
