"""product_dts

Revision ID: a67cdb4c03e7
Revises: 521cee0dee32
Create Date: 2025-05-18 17:05:07.160492

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a67cdb4c03e7"
down_revision: str | None = "521cee0dee32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("product", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("product", sa.Column("embedding_generated_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "embedding_generated_at")
    op.drop_column("product", "updated_at")
    op.drop_column("product", "created_at")
    # ### end Alembic commands ###
